services:
  mcp-proxy-custom:
    build:
      context: .
      dockerfile: mcp-proxy.Dockerfile
    network_mode: host
    restart: unless-stopped
    ports:
      - 8096:8096
    command:
      - "--pass-environment"
      - "--port=8096"
      - "--sse-host"
      - "0.0.0.0"
      - "--named-server-config"
      - "/config/mcp-proxy.json"
    volumes:
      - ./config/:/config/
volumes:
  config: